[package]
name = "atcoderstreak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "1.0.9"
toml = "0.8.10"
serde = "1.0.197"
chrono = "0.4.34"
line_notify = "0.2.1"
tokio = "1.36.0"
