[load_last_ac]
user_name = ""
address = "https://kenkoooo.com/atcoder"
user_id_selector = "#user_id"
user_button_selector = "#root > div > div.sticky-top > nav.border-bottom.navbar.navbar-expand-md.navbar-light.bg-light > ul > li:nth-child(2) > div > div:nth-child(1) > div > a:nth-child(3)"
last_ac_selector = "#root > div > div.my-5.container > div > div.my-3.row > div:nth-child(7) > h6.text-muted"

[compare_dates]
extra_text = "Last AC: "
date_format = "%Y-%m-%d"

[discord_notifier]
token = ""
channel_id = ""
message = """AtCoderのStreakが更新されていません
早く問題を解いてください
"""

[registerer]
task_name = "AtCoderStreak"
task_description = "AtCoderのStreakが更新されていない場合、設定した時刻にDiscordで通知します"
notify_times = [
    "18:00",
    "21:00",
    "22:00",
    "23:00",
    "23:15",
    "23:30",
    "23:45",
    "23:50",
    "23:55",
]
